# This is a basic workflow to help you get started with Actions

name: RunContainer
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: arc-runner-set
    container:
      image: chainguard/node:latest-dev
      env:
        NODE_ENV: development
      # ports:
      #   - 80
      # volumes:
      #   - my_docker_volume:/volume_mount
      # options: --cpus 1
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - name: check home
        run: |
          ls -la /github/home
          pwd
          ls -la
          find / -name README.md
      
