# This is a basic workflow to help you get started with Actions

name: RunContainer
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: arc-runner-set
    container:
      image: chainguard/wolfi-base
      env:
        NODE_ENV: development
      # ports:
      #   - 80
      # volumes:
      #   - my_docker_volume:/volume_mount
      # options: --cpus 1
    steps:
      - name: Install git
        run: apk add git
      - name: Checkout source code
        uses: actions/checkout@v4         
      - name: check home
        run: |
          pwd
          ls -la
      
