# This is a basic workflow to help you get started with Actions

name: RunContainer
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: arc-runner-set
    container:
      image: chainguard/node:latest-dev
      options: --user 0 
      # env:
      #   NODE_ENV: development
      # ports:
      #   - 80
      # volumes:
      #   - my_docker_volume:/volume_mount
      # options: --cpus 1
    steps:
      - name: check dirs
        run: |
          id
          pwd
          ls -la /__w
          ls -la /__w/_*
      - name: Checkout source code
        uses: actions/checkout@v6        
      - name: check home
        run: |
          id
          pwd
          ls -la
      
