# This is a basic workflow to help you get started with Actions

name: RunContainer
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: arc-runner-set
    container:
      # image: chainguard/node:latest-dev
      image: alpine
      options: --user 0 
      # env:
      #   NODE_ENV: development
      # ports:
      #   - 80
      # volumes:
      #   - my_docker_volume:/volume_mount
      # options: --cpus 1
    steps:
      - name: check dirs
        run: |
          id
          pwd
          echo "==== __w ===="
          ls -la /__w
          echo "==== __w/_* ===="
          ls -la /__w/_*
          echo "==== __wtemprunner ===="
          ls -la /__w/_temp/_runner_file_commands
          echo '==== __w temp *.sh ===='
          ls -l /__w/_temp/*.sh
          echo '==== __w loop ===='
          for n in /__w/_temp/*.sh ; do echo $n ; cat $n ; echo "====" ; done
          echo '==== ps ===='
          ps -ef
      # - name: Checkout source code
      #   uses: actions/checkout@v6        
      # - name: check home
      #   run: |
      #     id
      #     pwd
      #     ls -la
      
