name: Actions Runner Controller Demo
on:
  workflow_dispatch:
jobs:
  shellstuff:
    runs-on: arc-runner-set
    steps:
    - run: echo "ðŸŽ‰ This job uses runner scale set runners!"
    - run: id
    - run: hostname
    - run: sleep 3600
